apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pythonapp
  name: pythonapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonapp
  strategy: {}
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - image: docker.io/kuppusav/pythonapp:20
        name: pythonapp
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
  labels:
    app: pythonapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pythonapp
